#!/bin/bash

THIS_DIR=$PWD
cd ~
ln -s ${THIS_DIR}/.vimrc
ln -s ${THIS_DIR}/.vim

cd ${THIS_DIR}/.vim/
mkdir bundle
cd bundle
git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim
vim -c BundleInstall!
